services:
  zerotier:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_CODENAME_BUILD: noble
    image: zerotier:latest
    container_name: zerotier
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data:/var/lib/zerotier-one
    restart: unless-stopped

